version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manrakshak
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/manrakshak
    depends_on:
      - db

  web_dashboard:
    build:
      context: ./web_dashboard
    ports:
      - "8080:80"
    depends_on:
      - backend

  mobile_web_app:
    build:
      context: ./mobile_web_app
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  postgres_data:
