"""add_organization_settings

Revision ID: 077b4d81a29b
Revises: 0c751bff2d63
Create Date: 2026-09-02 23:28:38.984467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077b4d81a29b'
down_revision: Union[str, None] = '0c751bff2d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('checkin_frequency', sa.Enum('DAILY', 'PER_SHIFT', 'FLEXIBLE', name='checkinfrequency'), nullable=False),
    sa.Column('minimum_analytics_cohort_size', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_settings')
    # ### end Alembic commands ###
