"""initial schema

Revision ID: 0c751bff2d63
Revises: 
Create Date: 2026-09-01 16:59:43.743370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c751bff2d63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_organization_code'), 'organizations', ['organization_code'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('unit_code', sa.String(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='unitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'unit_code', name='uix_org_unit_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PERSONNEL', 'WELFARE_OFFICER', 'COMMANDER', 'ADMINISTRATOR', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_unit_id'), 'users', ['unit_id'], unique=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'VIEW_PERSONNEL', 'CREATE_WELLNESS_CHECKIN', 'CREATE_SUPPORT_REQUEST', 'VIEW_SUPPORT_REQUEST', 'CREATE_INTERVENTION', 'UPDATE_INTERVENTION', 'COMPLETE_INTERVENTION', 'RESCHEDULE_INTERVENTION', 'CREATE_USER', 'UPDATE_USER', 'DISABLE_USER', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('personnel_id', sa.String(), nullable=False),
    sa.Column('assigned_officer_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('WORKLOAD_REVIEW', 'RECOVERY_SUPPORT', 'WELLNESS_FOLLOWUP', 'GENERAL_WELFARE_SUPPORT', name='interventionactiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'RESCHEDULED', name='interventionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_assigned_officer_id'), 'interventions', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_interventions_follow_up_date'), 'interventions', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_interventions_personnel_id'), 'interventions', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_interventions_status'), 'interventions', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.Enum('FOLLOWUP', 'SUPPORT', 'TREND', 'REPORT', 'SYSTEM', 'SECURITY', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_resource', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_id'), 'refresh_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('personnel_id', sa.String(), nullable=False),
    sa.Column('request_type', sa.Enum('GENERAL_WELLBEING', 'WORKLOAD', 'FATIGUE', 'PERSONAL_SUPPORT', 'PRIVATE_DISCUSSION', name='supportrequesttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED', name='supportrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_created_at'), 'support_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_requests_personnel_id'), 'support_requests', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    op.create_table('wellness_checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('personnel_id', sa.String(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('workload_score', sa.Integer(), nullable=False),
    sa.Column('stress_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('energy_score >= 1 AND energy_score <= 5', name='check_energy_score'),
    sa.CheckConstraint('mood_score >= 1 AND mood_score <= 5', name='check_mood_score'),
    sa.CheckConstraint('sleep_hours >= 0 AND sleep_hours <= 24', name='check_sleep_hours'),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 5', name='check_sleep_quality'),
    sa.CheckConstraint('stress_score >= 1 AND stress_score <= 5', name='check_stress_score'),
    sa.CheckConstraint('workload_score >= 1 AND workload_score <= 5', name='check_workload_score'),
    sa.ForeignKeyConstraint(['personnel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_id', 'checkin_date', name='uix_personnel_checkin_date')
    )
    op.create_index(op.f('ix_wellness_checkins_checkin_date'), 'wellness_checkins', ['checkin_date'], unique=False)
    op.create_index(op.f('ix_wellness_checkins_personnel_id'), 'wellness_checkins', ['personnel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_checkins_personnel_id'), table_name='wellness_checkins')
    op.drop_index(op.f('ix_wellness_checkins_checkin_date'), table_name='wellness_checkins')
    op.drop_table('wellness_checkins')
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_personnel_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_created_at'), table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_interventions_status'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_personnel_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_follow_up_date'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_assigned_officer_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_unit_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_index(op.f('ix_organizations_organization_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
